version: '3.9'

services:
  sf:
    build: ./sf
    container_name: sf_c
    ports:
      - 50005:5000
    tty: true
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development

    volumes:
      - ./sf:/app

    command: flask run --host=0.0.0.0
